window.QUESTION_BANK = [
  {
    id: "devjourn-1",
    module: "Lesson 1",
    number: 1,
    topic: "Development Journalism",
    question: "1. Journalism has the purpose to empower the informed.",
    choices: ["True", "False"],
    answers: ["True"],
    matching: null,
    images: [],
    explanation: "From the reviewer: Journalism has the purpose to empower the informed.",
    gradable: true,
    raw: "Journalism has the purpose to empower the informed."
  },
  {
    id: "devjourn-2",
    module: "Lesson 1",
    number: 2,
    topic: "Development Journalism",
    question: "2. What does journalism provide people with?",
    choices: ["Entertainment only", "Information they need to make the best possible decisions", "Government propaganda", "Advertising slogans"],
    answers: ["Information they need to make the best possible decisions"],
    matching: null,
    images: [],
    explanation: "The reviewer says journalism provides people with the information they need to make the best possible decisions about their lives, communities, societies, and governments.",
    gradable: true,
    raw: "Journalism provides people with the information they need to make the best possible decisions."
  },
  {
    id: "devjourn-3",
    module: "Lesson 1",
    number: 3,
    topic: "Development Journalism",
    question: "3. Development Journalism is a type of writing and reporting on topics related to what process?",
    choices: ["Economic development", "Election campaigns", "Celebrity media", "Sports broadcasting"],
    answers: ["Economic development"],
    matching: null,
    images: [],
    explanation: "The reviewer defines Development Journalism as writing and reporting on topics related to the process of economic development.",
    gradable: true,
    raw: "Development Journalism a type of writing and reporting on topics related to the process of economic development."
  },
  {
    id: "devjourn-4",
    module: "Lesson 1",
    number: 4,
    topic: "Development Journalism",
    question: "4. Development journalism is sometimes called what? (Choose two.)",
    choices: ["development support communication", "government say-so journalism", "market journalism", "celebrity journalism"],
    answers: ["development support communication", "government say-so journalism"],
    matching: null,
    images: [],
    explanation: "The reviewer says it is sometimes called development support communication or government say-so journalism.",
    gradable: true,
    raw: "Sometimes called as development support communication or government say-so journalism."
  },
  {
    id: "devjourn-5",
    module: "Lesson 1",
    number: 5,
    topic: "Development Journalism",
    question: "5. Match the news value of development journalism to its order in the reviewer.",
    choices: [],
    answers: [],
    matching: {
      targets: ["1", "2", "3", "4", "5"],
      options: ["Development", "Social Responsibility", "Education", "National Integration", "Human interest"],
      answers: {
        "1": "Development",
        "2": "Social Responsibility",
        "3": "Education",
        "4": "National Integration",
        "5": "Human interest"
      }
    },
    images: [],
    explanation: "News Values of Development Journalism: Development, Social Responsibility, Education, National Integration, Human interest.",
    gradable: true,
    raw: "News Values of Development Journalism"
  },
  {
    id: "devjourn-6",
    module: "Lesson 1",
    number: 6,
    topic: "Sustainable Development Goals",
    question: "6. How many Sustainable Development Goals are listed in the reviewer?",
    choices: ["10", "12", "15", "17"],
    answers: ["17"],
    matching: null,
    images: [],
    explanation: "The reviewer lists Sustainable Development Goals numbered 1 through 17.",
    gradable: true,
    raw: "SUSTAINABLE DEVELOPMENT GOALS: 1 through 17."
  },
  {
    id: "devjourn-7",
    module: "Lesson 1",
    number: 7,
    topic: "Sustainable Development Goals",
    question: "7. Which item is one of the Sustainable Development Goals listed in the reviewer?",
    choices: ["Clean Water and Sanitation", "Higher Advertising Revenue", "Press Subsidy", "Market Centralization"],
    answers: ["Clean Water and Sanitation"],
    matching: null,
    images: [],
    explanation: "Goal 6 in the reviewer is Clean Water and Sanitation.",
    gradable: true,
    raw: "6. Clean Water and Sanitation"
  },
  {
    id: "devjourn-8",
    module: "Lesson 1",
    number: 8,
    topic: "Development Journalism",
    question: "8. In the Second Development Decade, development was defined as what?",
    choices: ["The improvement of the quality of life of the individual", "The growth of advertising markets", "The control of media by political elites", "The replacement of community broadcasting"],
    answers: ["The improvement of the quality of life of the individual"],
    matching: null,
    images: [],
    explanation: "The reviewer says development was defined as the improvement of the quality of life of the individual.",
    gradable: true,
    raw: "Development was defined as the improvement of the quality of life of the individual."
  },
  {
    id: "devjourn-9",
    module: "Lesson 1",
    number: 9,
    topic: "Development Journalism",
    question: "9. Which items are listed as indicators in the reviewer? (Choose three.)",
    choices: ["Enough food, clothing, footwear and shelter", "meaning employment", "equality education", "Click-through rate", "Private enterprise"],
    answers: ["Enough food, clothing, footwear and shelter", "meaning employment", "equality education"],
    matching: null,
    images: [],
    explanation: "The reviewer lists indicators such as enough food, clothing, footwear and shelter; meaning employment; equality education.",
    gradable: true,
    raw: "Indicators: Enough food, clothing, footwear and shelter; meaning employment; equality education"
  },
  {
    id: "devjourn-10",
    module: "Lesson 1",
    number: 10,
    topic: "Development Journalism",
    question: "10. A feature on development journalism may cover which issue?",
    choices: ["Agriculture and Food Security", "Only celebrity gossip", "Only sports scores", "Only product placement"],
    answers: ["Agriculture and Food Security"],
    matching: null,
    images: [],
    explanation: "The reviewer lists Agriculture and Food Security as one issue a feature on development journalism may cover.",
    gradable: true,
    raw: "A Feature on development journalism may cover: Agriculture and Food Security."
  },
  {
    id: "devjourn-11",
    module: "Lesson 1",
    number: 11,
    topic: "Development Journalism",
    question: "11. Match the perspective of Development Journalism to the wording in the reviewer.",
    choices: [],
    answers: [],
    matching: {
      targets: ["1", "2", "3", "4"],
      options: ["Journalists as Nation Builders", "Journalists as Government Partners", "Journalists as Agents of Empowerment", "Journalists as Watchdogs and Guardians of Transparency"],
      answers: {
        "1": "Journalists as Nation Builders",
        "2": "Journalists as Government Partners",
        "3": "Journalists as Agents of Empowerment",
        "4": "Journalists as Watchdogs and Guardians of Transparency"
      }
    },
    images: [],
    explanation: "Perspective of Development Journalism: Journalists as Nation Builders; Government Partners; Agents of Empowerment; Watchdogs and Guardians of Transparency.",
    gradable: true,
    raw: "Perspective of Development Journalism"
  },
  {
    id: "devjourn-12",
    module: "Lesson 1",
    number: 12,
    topic: "Development Journalism",
    question: "12. Bottom up reporting results in news that includes whose voices and perspectives?",
    choices: ["People most adversely affected by modernization", "Only advertisers", "Only political elites", "Only celebrities"],
    answers: ["People most adversely affected by modernization"],
    matching: null,
    images: [],
    explanation: "The reviewer says bottom up reporting includes the voices and perspectives of people most adversely affected by modernization.",
    gradable: true,
    raw: "Bottom up reporting results in news that includes the voices and perspectives of people most adversely affected by modernization."
  },
  {
    id: "devjourn-13",
    module: "Lesson 1",
    number: 13,
    topic: "Development Journalism",
    question: "13. Development journalism was conceived in the 1960s at what organization?",
    choices: ["Press Foundation of Asia", "Roman Church", "World Bank", "Soul City Institute"],
    answers: ["Press Foundation of Asia"],
    matching: null,
    images: [],
    explanation: "The reviewer says Development journalism was conceived in the 1960s at the Press Foundation of Asia.",
    gradable: true,
    raw: "Development journalism was conceived in the 1960s at the Press Foundation of Asia (PFA)."
  },
  {
    id: "devjourn-14",
    module: "Lesson 1",
    number: 14,
    topic: "Development Journalism",
    question: "14. Which Filipino journalists were concerned that news organizations were inadequately covering socioeconomic development?",
    choices: ["Alan Chalkley and Juan Mercado", "McGann and Johnstone", "Thomas McPhail and Paulo Freire", "Bob Geldof and Beckham"],
    answers: ["Alan Chalkley and Juan Mercado"],
    matching: null,
    images: [],
    explanation: "The reviewer names Filipino journalists Alan Chalkley and Juan Mercado.",
    gradable: true,
    raw: "Filipino journalists Alan Chalkley and Juan Mercado were concerned that news organizations were inadequately covering socioeconomic development."
  },
  {
    id: "devjourn-15",
    module: "Lesson 2",
    number: 15,
    topic: "Press Theories",
    question: "15. Which theory says the state ranks higher than the individuals in the scale of social values?",
    choices: ["Authoritarianism", "Libertarianism", "Social Responsibility", "Entertainment-Education"],
    answers: ["Authoritarianism"],
    matching: null,
    images: [],
    explanation: "The reviewer says an essential characteristic of an authoritarian society is that the state ranks higher than the individuals.",
    gradable: true,
    raw: "An essential characteristic of an authoritarian society is that the state ranks higher than the individuals in the scale of social values."
  },
  {
    id: "devjourn-16",
    module: "Lesson 2",
    number: 16,
    topic: "Press Theories",
    question: "16. Match the theory of the press to the clue.",
    choices: [],
    answers: [],
    matching: {
      targets: ["Authoritarianism", "Soviet Communist Theory", "Libertarianism", "Social Responsibility"],
      options: ["the state ranks higher than the individuals", "the state owns or controls all forms of mass media directly", "trust the self-righting process of truth", "private ownership of mass media in exchange for responsible use"],
      answers: {
        "Authoritarianism": "the state ranks higher than the individuals",
        "Soviet Communist Theory": "the state owns or controls all forms of mass media directly",
        "Libertarianism": "trust the self-righting process of truth",
        "Social Responsibility": "private ownership of mass media in exchange for responsible use"
      }
    },
    images: [],
    explanation: "The reviewer describes these clues under the Four Concepts of Mass Communication.",
    gradable: true,
    raw: "Four Concepts of Mass Communication"
  },
  {
    id: "devjourn-17",
    module: "Lesson 2",
    number: 17,
    topic: "Press Theories",
    question: "17. Soviet Communist Theory started in what year according to the reviewer?",
    choices: ["1450", "1918", "1960", "2001"],
    answers: ["1918"],
    matching: null,
    images: [],
    explanation: "The reviewer states Soviet Communist Theory started 1918 until now.",
    gradable: true,
    raw: "Started 1918 until now"
  },
  {
    id: "devjourn-18",
    module: "Lesson 2",
    number: 18,
    topic: "Press Theories",
    question: "18. Libertarianism chooses to trust what process?",
    choices: ["Self-righting process of truth", "Government censorship", "Manipulative advertising", "Unofficial intimidation"],
    answers: ["Self-righting process of truth"],
    matching: null,
    images: [],
    explanation: "The reviewer says libertarianism chooses to trust the self-righting process of truth.",
    gradable: true,
    raw: "Libertarianism chooses to trust the self-righting the process of truth."
  },
  {
    id: "devjourn-19",
    module: "Lesson 2",
    number: 19,
    topic: "Press Theories",
    question: "19. Development Communication Journalism is argued as what theory of the press?",
    choices: ["Fifth Theory of the Press", "First Theory of the Press", "Only a branch of advertising", "A type of entertainment only"],
    answers: ["Fifth Theory of the Press"],
    matching: null,
    images: [],
    explanation: "The reviewer says Development Communication Journalism is the Fifth Theory of the Press.",
    gradable: true,
    raw: "Argued with little reservation that this is the Fifth Theory of the Press."
  },
  {
    id: "devjourn-20",
    module: "Lesson 2",
    number: 20,
    topic: "Development Communication",
    question: "20. What is the chief purpose of Development Communication Journalism?",
    choices: ["Social transformation and development", "Maximizing political subsidy", "Celebrity promotion", "Monopoly protection"],
    answers: ["Social transformation and development"],
    matching: null,
    images: [],
    explanation: "The reviewer lists the chief purpose as Social transformation and development - society as whole.",
    gradable: true,
    raw: "Chief purpose: Social transformation and development - society as whole."
  },
  {
    id: "devjourn-21",
    module: "Writing",
    number: 21,
    topic: "Writing",
    question: "21. What is the goal of writing development journalism?",
    choices: ["commit for a positive change", "create emotional famous", "rely on academic jargon", "avoid affected voices"],
    answers: ["commit for a positive change"],
    matching: null,
    images: [],
    explanation: "The reviewer states the goal of writing development journalism is to commit for a positive change.",
    gradable: true,
    raw: "The goal of writing development journalism is to commit for a positive change."
  },
  {
    id: "devjourn-22",
    module: "Writing",
    number: 22,
    topic: "Strategies",
    question: "22. Which strategy means 'nation building' in the reviewer?",
    choices: ["Framing", "Accountability", "Humanization", "Solution Oriented"],
    answers: ["Framing"],
    matching: null,
    images: [],
    explanation: "Under Strategies in DevJourn, the reviewer lists Framing - 'nation building'.",
    gradable: true,
    raw: "1. Framing - 'nation building'"
  },
  {
    id: "devjourn-23",
    module: "Writing",
    number: 23,
    topic: "Strategies",
    question: "23. Which strategy asks the journalist to show flaws in the given response?",
    choices: ["Highlight limitations and challenges", "Avoid parachute", "Build trust first", "Private enterprise"],
    answers: ["Highlight limitations and challenges"],
    matching: null,
    images: [],
    explanation: "The reviewer says Highlight limitations and challenges means logistical issues, pointing out the flaws of the given response.",
    gradable: true,
    raw: "Highlight limitations and challenges - logistical issues, pointing out the flaws of the given response."
  },
  {
    id: "devjourn-24",
    module: "Writing",
    number: 24,
    topic: "Strategies",
    question: "24. In investigative development journalism, what should the writer lead with?",
    choices: ["Human impact", "Academic jargon", "The advertiser", "The celebrity first"],
    answers: ["Human impact"],
    matching: null,
    images: [],
    explanation: "The reviewer says Lead with human impact - start with a compelling story/character.",
    gradable: true,
    raw: "Lead with human impact - start with a compelling story/character."
  },
  {
    id: "devjourn-25",
    module: "Writing",
    number: 25,
    topic: "Ethics",
    question: "25. Which is listed under Ethical Reporting in DevJourn?",
    choices: ["Build Trust First", "Sensationalize", "Avoid affected voices", "Rely on academic jargon"],
    answers: ["Build Trust First"],
    matching: null,
    images: [],
    explanation: "The reviewer lists Build Trust First under Ethical Reporting in DevJourn.",
    gradable: true,
    raw: "ETHICAL REPORTING IN DEVJOURN: Build Trust First."
  },
  {
    id: "devjourn-26",
    module: "Writing",
    number: 26,
    topic: "Visual Storytelling",
    question: "26. Visual storytelling in DevJourn says to approach as what?",
    choices: ["One human to another", "A celebrity to an audience", "A political elite to the public", "A sponsor to a buyer"],
    answers: ["One human to another"],
    matching: null,
    images: [],
    explanation: "The reviewer lists Approach as one human to another.",
    gradable: true,
    raw: "Approach as one human to another"
  },
  {
    id: "devjourn-27",
    module: "Writing",
    number: 27,
    topic: "Visual Storytelling",
    question: "27. Which is more important than audio in documentaries according to the reviewer?",
    choices: ["Visual", "Jargon", "Advertising", "Political subsidy"],
    answers: ["Visual"],
    matching: null,
    images: [],
    explanation: "The reviewer says Visual is more important than audio in documentaries.",
    gradable: true,
    raw: "Visual is more important than audio in documentaries."
  },
  {
    id: "devjourn-28",
    module: "Lesson 3",
    number: 28,
    topic: "Development Communication",
    question: "28. Development communication aims to achieve what kind of change?",
    choices: ["Positive social change", "Only commercial profit", "Only celebrity awareness", "Only government censorship"],
    answers: ["Positive social change"],
    matching: null,
    images: [],
    explanation: "The reviewer says the goal is to achieve positive social change.",
    gradable: true,
    raw: "Goal: achieve positive social change"
  },
  {
    id: "devjourn-29",
    module: "Lesson 3",
    number: 29,
    topic: "DevComm Theories",
    question: "29. Cultural Imperialism Theory is also called what?",
    choices: ["Silent Colonization", "Bottom up reporting", "Self-righting truth", "Public Information Office"],
    answers: ["Silent Colonization"],
    matching: null,
    images: [],
    explanation: "The reviewer labels Cultural Imperialism Theory as Silent Colonization.",
    gradable: true,
    raw: "CULTURAL IMPERIALISM THEORY (SILENT COLONIZATION)"
  },
  {
    id: "devjourn-30",
    module: "Lesson 3",
    number: 30,
    topic: "DevComm Theories",
    question: "30. Cultural Imperialism Theory states that a dominant socio-political group influences and shapes the culture of what?",
    choices: ["the weaker group of nations through mass media", "Only the state broadcaster", "Only private enterprise", "Only NGOs"],
    answers: ["the weaker group of nations through mass media"],
    matching: null,
    images: [],
    explanation: "The reviewer states that a dominant socio-political group influences and shapes the culture of the weaker group of nations through mass media.",
    gradable: true,
    raw: "State that a dominant socio-political group influences and shapes the culture of the weaker group of nations through mass media."
  },
  {
    id: "devjourn-31",
    module: "Lesson 3",
    number: 31,
    topic: "DevComm Theories",
    question: "31. Match Paulo Freire's model concepts to their reviewer clues.",
    choices: [],
    answers: [],
    matching: {
      targets: ["Dialogue", "Conscientization", "Praxis", "Transformation", "Critical Consciousness"],
      options: ["back and forth communication", "awareness", "examination of the theory and real-world practice", "execution of the theory", "active social and political involvement"],
      answers: {
        "Dialogue": "back and forth communication",
        "Conscientization": "awareness",
        "Praxis": "examination of the theory and real-world practice",
        "Transformation": "execution of the theory",
        "Critical Consciousness": "active social and political involvement"
      }
    },
    images: [],
    explanation: "The reviewer lists Dialogue, Conscientization, Praxis, Transformation, and Critical Consciousness under Paul Freire's Model of Communication.",
    gradable: true,
    raw: "Paul Freire's Model of Communication"
  },
  {
    id: "devjourn-32",
    module: "Lesson 3",
    number: 32,
    topic: "DevComm Theories",
    question: "32. Entertainment-Education Theory is described as what?",
    choices: ["Communication strategy and process by which media messages are planned and created", "A press censorship rule", "A type of community broadcasting", "A theory of celebrity campaigns"],
    answers: ["Communication strategy and process by which media messages are planned and created"],
    matching: null,
    images: [],
    explanation: "The reviewer says Entertainment-Education Theory is a communication strategy and process by which media messages are planned and created.",
    gradable: true,
    raw: "Communication strategy and process by which media messages are planned and created."
  },
  {
    id: "devjourn-33",
    module: "Lesson 3",
    number: 33,
    topic: "ICT4D",
    question: "33. What does ICT4D stand for?",
    choices: ["Information and Communication Technologies for Development", "International Communication Theory for Democracy", "Internet Control Tools for Development", "Information Campaign Training for Documentaries"],
    answers: ["Information and Communication Technologies for Development"],
    matching: null,
    images: [],
    explanation: "The reviewer defines ICT4D as Information and Communication Technologies for Development.",
    gradable: true,
    raw: "Information and Communication Technologies for Development."
  },
  {
    id: "devjourn-34",
    module: "Lesson 3",
    number: 34,
    topic: "ICT4D",
    question: "34. ICT4D was initiated to bridge what?",
    choices: ["Digital divide", "Social responsibility", "Press ownership", "Celebrity campaigns"],
    answers: ["Digital divide"],
    matching: null,
    images: [],
    explanation: "The reviewer says ICT4D was initiated to bridge the digital divide.",
    gradable: true,
    raw: "ICT4D initiated to bridge the digital divide."
  },
  {
    id: "devjourn-35",
    module: "Lesson 3",
    number: 35,
    topic: "ICT4D",
    question: "35. Which are causes of digital divide? (Choose four.)",
    choices: ["Education and digital literacy", "Income levels", "Geographical restrictions", "Motivation and general interest", "Router priority", "Press releases"],
    answers: ["Education and digital literacy", "Income levels", "Geographical restrictions", "Motivation and general interest"],
    matching: null,
    images: [],
    explanation: "The reviewer lists causes of digital divide: Education and Digital Literacy, Income Levels, Geographical Restrictions, Motivation and General Interest.",
    gradable: true,
    raw: "CAUSES OF DIGITAL DIVIDE"
  },
  {
    id: "devjourn-36",
    module: "Lesson 3",
    number: 36,
    topic: "Communication Planning",
    question: "36. Communication planning is described as what?",
    choices: ["A policy-driven approach to providing stakeholders with information", "A type of celebrity campaign", "A routing protocol", "A market monopoly"],
    answers: ["A policy-driven approach to providing stakeholders with information"],
    matching: null,
    images: [],
    explanation: "The reviewer says Communication Planning is a policy-driven approach to providing stakeholders with information.",
    gradable: true,
    raw: "A policy-driven approach to providing stakeholders with information."
  },
  {
    id: "devjourn-37",
    module: "Lesson 3",
    number: 37,
    topic: "Communication Planning",
    question: "37. Match the ABCD approach to Communication Objective Formulation.",
    choices: [],
    answers: [],
    matching: {
      targets: ["Audience", "Behavior", "Condition", "Degree"],
      options: ["Specify a single priority intended group", "Define the type of change/s you expect", "Determine when and under what condition these changes to occur", "Specify how much change you expect and how to find out it happened"],
      answers: {
        "Audience": "Specify a single priority intended group",
        "Behavior": "Define the type of change/s you expect",
        "Condition": "Determine when and under what condition these changes to occur",
        "Degree": "Specify how much change you expect and how to find out it happened"
      }
    },
    images: [],
    explanation: "The reviewer lists Audience, Behavior, Condition, Degree under the ABCD Approach.",
    gradable: true,
    raw: "ABCD Approach in Communication Objective Formulation"
  },
  {
    id: "devjourn-38",
    module: "Lesson 3",
    number: 38,
    topic: "Communication Planning",
    question: "38. Focused Audience refers to what?",
    choices: ["specific audience whose knowledge, attitude, and/or behavior toward an issue should be changed", "All advertisers in a market", "Only national government", "Only broadcasters"],
    answers: ["specific audience whose knowledge, attitude, and/or behavior toward an issue should be changed"],
    matching: null,
    images: [],
    explanation: "The reviewer defines Focused Audience as the specific audience whose knowledge, attitude, and or behavior toward an issue should be changed.",
    gradable: true,
    raw: "Focused Audience"
  },
  {
    id: "devjourn-39",
    module: "Lesson 4",
    number: 39,
    topic: "NGOs",
    question: "39. According to the reviewer, what is believed to be the first NGO?",
    choices: ["Anti-Slavery Society", "World Wildlife Fund", "Soul City Institute", "Press Foundation of Asia"],
    answers: ["Anti-Slavery Society"],
    matching: null,
    images: [],
    explanation: "The reviewer states 1839, believed first NGO is Anti-Slavery Society.",
    gradable: true,
    raw: "1839, believed first NGO is Anti-Slavery Society"
  },
  {
    id: "devjourn-40",
    module: "Lesson 4",
    number: 40,
    topic: "NGOs",
    question: "40. Match the roles of NGOs to their order in the reviewer.",
    choices: [],
    answers: [],
    matching: {
      targets: ["1", "2", "3", "4"],
      options: ["Social Development", "Sustainable Community Development", "Sustainable Development", "Sustainable Consumption"],
      answers: {
        "1": "Social Development",
        "2": "Sustainable Community Development",
        "3": "Sustainable Development",
        "4": "Sustainable Consumption"
      }
    },
    images: [],
    explanation: "The reviewer lists Social Development, Sustainable Community Development, Sustainable Development, and Sustainable Consumption.",
    gradable: true,
    raw: "4 Roles of NGOs"
  },
  {
    id: "devjourn-41",
    module: "Lesson 4",
    number: 41,
    topic: "Community Broadcasting",
    question: "41. What are the two main types of community in community broadcasting?",
    choices: ["Geographic Communities; Communities of Interest", "Digital divide and social divide", "Audience and behavior", "Dialogue and praxis"],
    answers: ["Geographic Communities; Communities of Interest"],
    matching: null,
    images: [],
    explanation: "The reviewer lists Geographic Communities and Communities of Interest.",
    gradable: true,
    raw: "TWO MAIN TYPES: Geographic Communities; Communities of Interest."
  },
  {
    id: "devjourn-42",
    module: "Lesson 4",
    number: 42,
    topic: "Community Broadcasting",
    question: "42. Community broadcasting should operate in whose interest?",
    choices: ["Public interest", "Only advertisers' interest", "Only celebrity interest", "Only party leaders' interest"],
    answers: ["Public interest"],
    matching: null,
    images: [],
    explanation: "The reviewer says Community Broadcasting should operate in the public interest and serve the voice and information need of the community.",
    gradable: true,
    raw: "Comm Broad should operate in the public interest."
  },
  {
    id: "devjourn-43",
    module: "Lesson 4",
    number: 43,
    topic: "PIO",
    question: "43. What must a Public Information Office create and enable?",
    choices: ["Clear and concise communication", "Only celebrity events", "Routing tables", "Advertising monopolies"],
    answers: ["Clear and concise communication"],
    matching: null,
    images: [],
    explanation: "The reviewer says PIO must create and enable clear and concise communication.",
    gradable: true,
    raw: "Must create and enable clear and concise communication."
  },
  {
    id: "devjourn-44",
    module: "Lesson 4",
    number: 44,
    topic: "Celebrity Media",
    question: "44. Campaign started by Bob Geldof, an Irish singer-songwriter, in what year?",
    choices: ["2001", "1839", "1918", "1960"],
    answers: ["2001"],
    matching: null,
    images: [],
    explanation: "The reviewer says Campaign started by Bob Geldof, an Irish singer-songwriter in 2001.",
    gradable: true,
    raw: "Campaign started by Bob Geldof, an Irish singer-songwriter in 2001."
  },
  {
    id: "devjourn-45",
    module: "Writing",
    number: 45,
    topic: "Do and Don't",
    question: "45. Which is a DO in DevJourn according to the reviewer?",
    choices: ["Use active, present tense verbs", "Use passive or vague doom headline", "Rely on academic jargon", "Sensationalize"],
    answers: ["Use active, present tense verbs"],
    matching: null,
    images: [],
    explanation: "The reviewer says Do use active, present tense verbs to convey movement of urgency.",
    gradable: true,
    raw: "Do use active, present tense verbs to convey movement of urgency."
  },
  {
    id: "devjourn-46",
    module: "Lesson 2",
    number: 46,
    topic: "Press Theories",
    question: "46. In Social Responsibility theory, private media ownership is allowed in exchange for what?",
    choices: ["responsible use of that media", "complete state ownership", "political subsidy only", "removing public criticism"],
    answers: ["responsible use of that media"],
    matching: null,
    images: [],
    explanation: "The reviewer states that Social Responsibility provides for private ownership of mass media in exchange for responsible use of that media.",
    gradable: true,
    raw: "Social Responsibility provides for private ownership of mass media in exchange for responsible use of that media."
  },
  {
    id: "devjourn-47",
    module: "Lesson 2",
    number: 47,
    topic: "Development Communication",
    question: "47. Which items are listed as forbidden under the Development Communication Journalism notes? (Choose three.)",
    choices: ["Monopolies", "Government propaganda", "Manipulative advertising", "Bottom-up reporting", "Community ownership"],
    answers: ["Monopolies", "Government propaganda", "Manipulative advertising"],
    matching: null,
    images: [],
    explanation: "The notes list forbidden items such as monopolies, government propaganda, manipulative advertising, immorality/obscenity, and inanities.",
    gradable: true,
    raw: "What are forbidden? Monopolies; Government propaganda; Manipulative advertising; Immorality/obscenity, Inanities."
  },
  {
    id: "devjourn-48",
    module: "Lesson 2",
    number: 48,
    topic: "Development Communication",
    question: "48. Development Communication Journalism is appropriate for what kind of world according to the reviewer?",
    choices: ["the developing world and its current global environment", "only celebrity-driven campaigns", "only authoritarian states", "only commercial advertising markets"],
    answers: ["the developing world and its current global environment"],
    matching: null,
    images: [],
    explanation: "The reviewer describes Development Communication Journalism as appropriate given the social and political structures of the developing world and its current global environment.",
    gradable: true,
    raw: "It is the appropriate system given the social and political structures of the developing world and its current global environment."
  },
  {
    id: "devjourn-49",
    module: "Lesson 2",
    number: 49,
    topic: "Development Communication",
    question: "49. Which are listed under ownership in the Development Communication Journalism notes? (Choose two.)",
    choices: ["Development agencies", "Communities", "Manipulative advertising", "Monopolies"],
    answers: ["Development agencies", "Communities"],
    matching: null,
    images: [],
    explanation: "The reviewer lists development agencies and communities under ownership, then explains that non-profit ownership is not limited to government and may be purposively employed for social transformation.",
    gradable: true,
    raw: "Ownership: Development agencies; Communities. Although it is non-profit, ownership is not limited to the government sector. Although it may not be controlled by the state, it is purposively employed for social transformation."
  },
  {
    id: "devjourn-50",
    module: "Writing",
    number: 50,
    topic: "Writing",
    question: "50. In writing for Development Journalism, what should happen after producing the story?",
    choices: ["there has to be an action itself", "the journalist should stop at awareness", "the case study should be hidden", "the response should be ignored"],
    answers: ["there has to be an action itself"],
    matching: null,
    images: [],
    explanation: "The reviewer notes that after producing, next is public opinion, and there has to be an action itself.",
    gradable: true,
    raw: "After producing, next is public opinion. There has to be an action itself."
  },
  {
    id: "devjourn-51",
    module: "Writing",
    number: 51,
    topic: "Strategies",
    question: "51. Match the DevJourn strategy to the learning cue from the reviewer.",
    choices: [],
    answers: [],
    matching: {
      targets: ["Framing", "Accountability", "Humanization", "Solution-oriented"],
      options: ["nation building", "examining the gap scheme and actual impact", "laymanize and focus on the human dimension", "highlighting success stories of people adopting new technologies or methods"],
      answers: {
        "Framing": "nation building",
        "Accountability": "examining the gap scheme and actual impact",
        "Humanization": "laymanize and focus on the human dimension",
        "Solution-oriented": "highlighting success stories of people adopting new technologies or methods"
      }
    },
    images: [],
    explanation: "The reviewer connects framing with nation-building, accountability with gaps and impact, humanization with laymanizing and the human dimension, and solution-oriented writing with success stories.",
    gradable: true,
    raw: "Strategies in DevJourn: Framing; Accountability; Humanization; Solution Oriented."
  },
  {
    id: "devjourn-52",
    module: "Writing",
    number: 52,
    topic: "Strategies",
    question: "52. If a DevJourn story uses a case study and lived experience, which requirement is it following?",
    choices: ["Main subjects", "Router priority", "Soviet ownership", "Celebrity framing"],
    answers: ["Main subjects"],
    matching: null,
    images: [],
    explanation: "Under requirements, the reviewer says the main subjects of DevJourn focus on case studies and lived experiences.",
    gradable: true,
    raw: "Main subjects: DevJourn focuses on the case studies, lived experiences."
  },
  {
    id: "devjourn-53",
    module: "Writing",
    number: 53,
    topic: "Strategies",
    question: "53. What should a Development Journalism story consider according to the notes on perspective?",
    choices: ["solution/perspective journalism approach", "only the advertiser's angle", "only celebrity visibility", "only government say-so"],
    answers: ["solution/perspective journalism approach"],
    matching: null,
    images: [],
    explanation: "The reviewer says DevJourn has to be interventionist and should consider the solution/perspective journalism approach.",
    gradable: true,
    raw: "It has to be interventionist - consider the solution/perspective journalism approach."
  },
  {
    id: "devjourn-54",
    module: "Writing",
    number: 54,
    topic: "Strategies",
    question: "54. In investigative development journalism, what should the writer identify first?",
    choices: ["the systematic angle", "the celebrity sponsor", "the router interface", "the advertising budget"],
    answers: ["the systematic angle"],
    matching: null,
    images: [],
    explanation: "The reviewer says to identify the systematic angle and anchor the piece of the story.",
    gradable: true,
    raw: "Identify the systematic angle - you anchored the piece of the story."
  },
  {
    id: "devjourn-55",
    module: "Writing",
    number: 55,
    topic: "Strategies",
    question: "55. Which investigative DevJourn step means checking the existing response?",
    choices: ["Examine the response", "Avoid affected voices", "Use passive headline", "Focus on process equipment"],
    answers: ["Examine the response"],
    matching: null,
    images: [],
    explanation: "The reviewer says Examine the response, also called the Solution Approach, means checking the existing response.",
    gradable: true,
    raw: "Examine the response (Solution Approach) - we check the existing response."
  },
  {
    id: "devjourn-56",
    module: "Writing",
    number: 56,
    topic: "Do and Don't",
    question: "56. Which pair correctly matches a DevJourn writing do and don't?",
    choices: ["Do pair the problem with the response; don't rely on academic jargon or acronym", "Do sensationalize; don't use active verbs", "Do use vague doom headline; don't add context", "Do remove affected voices; don't include response"],
    answers: ["Do pair the problem with the response; don't rely on academic jargon or acronym"],
    matching: null,
    images: [],
    explanation: "The reviewer lists do pair the problem with the response whenever applicable and don't rely on academic jargon or acronym.",
    gradable: true,
    raw: "Do pair the problem with the response whenever applicable. Don't rely on academic jargon or acronym."
  },
  {
    id: "devjourn-57",
    module: "Writing",
    number: 57,
    topic: "Ethics",
    question: "57. Which items are part of Ethical Reporting in DevJourn? (Choose three.)",
    choices: ["Build Trust First", "Avoid Parachute", "Keep tone constructive", "Sensationalize", "Use passive headline"],
    answers: ["Build Trust First", "Avoid Parachute", "Keep tone constructive"],
    matching: null,
    images: [],
    explanation: "Ethical reporting in the reviewer includes Build Trust First, Avoid Parachute, keep tone constructive, and don't sensationalize.",
    gradable: true,
    raw: "Ethical Reporting in DevJourn: Build Trust First; Avoid Parachute; Keep tone constructive; Don't sensationalize."
  },
  {
    id: "devjourn-58",
    module: "Writing",
    number: 58,
    topic: "Visual Storytelling",
    question: "58. Match each visual storytelling item to the order listed in the reviewer.",
    choices: [],
    answers: [],
    matching: {
      targets: ["1", "2", "3"],
      options: ["Approach as one human to another", "Listen before taking photos", "Build trust over time"],
      answers: {
        "1": "Approach as one human to another",
        "2": "Listen before taking photos",
        "3": "Build trust over time"
      }
    },
    images: [],
    explanation: "The visual storytelling section lists approach as one human to another, listen before taking photos, and build trust over time.",
    gradable: true,
    raw: "Visual Storytelling in DevJourn: 1. Approach as one human to another; 2. Listen before taking photos; 3. Build trust over time."
  },
  {
    id: "devjourn-59",
    module: "Lesson 3",
    number: 59,
    topic: "Development Communication",
    question: "59. Development communication can create what kinds of change? (Choose four.)",
    choices: ["Social", "Economic", "Personal", "Cultural", "Telnet", "Advertising monopoly"],
    answers: ["Social", "Economic", "Personal", "Cultural"],
    matching: null,
    images: [],
    explanation: "The reviewer says change could be social, economic, personal, spiritual, cultural, or political.",
    gradable: true,
    raw: "Change could be: Social, Economic, Personal, Spiritual, Cultural, Political."
  },
  {
    id: "devjourn-60",
    module: "Lesson 3",
    number: 60,
    topic: "DevComm Theories",
    question: "60. In Cultural Imperialism Theory, mass media is used as what?",
    choices: ["a propaganda tool to control and influence", "a router gateway", "a pure entertainment hobby", "a private diary"],
    answers: ["a propaganda tool to control and influence"],
    matching: null,
    images: [],
    explanation: "The reviewer says mass media is used as a propaganda tool to control and influence for economic and political benefit of the dominant party.",
    gradable: true,
    raw: "Mass Media is used as propaganda tool to control and influence for economic and political benefit of the dominant party."
  },
  {
    id: "devjourn-61",
    module: "Lesson 3",
    number: 61,
    topic: "DevComm Theories",
    question: "61. Participatory Communication Theory places special emphasis on development of what?",
    choices: ["the third world", "celebrity media", "router interfaces", "advertising monopolies"],
    answers: ["the third world"],
    matching: null,
    images: [],
    explanation: "The reviewer says Participatory Communication Theory focuses on effects of individuals on small communication with special emphasis on development of the third world.",
    gradable: true,
    raw: "Participatory Communication Theory focuses on the effects of individuals on small communication with the special emphasis placed on the development of the third world."
  },
  {
    id: "devjourn-62",
    module: "Lesson 3",
    number: 62,
    topic: "DevComm Theories",
    question: "62. Which problem is listed under Participatory Communication?",
    choices: ["Monitoring, evaluation, and implementation become difficult", "Private media owns everything", "Only celebrities can participate", "No translation issues exist"],
    answers: ["Monitoring, evaluation, and implementation become difficult"],
    matching: null,
    images: [],
    explanation: "The reviewer lists monitoring, evaluation, and implementation becoming difficult as a problem with participatory communication.",
    gradable: true,
    raw: "Problems with Participatory Communication: Monitoring, evaluation, and implementation become difficult."
  },
  {
    id: "devjourn-63",
    module: "Lesson 3",
    number: 63,
    topic: "DevComm Theories",
    question: "63. Entertainment-Education Theory captures attention by using what medium behavior from audiences?",
    choices: ["many people see social media as an entertainment factor", "audiences reject all entertainment", "people only listen to print newspapers", "digital divide removes all media messages"],
    answers: ["many people see social media as an entertainment factor"],
    matching: null,
    images: [],
    explanation: "The reviewer says many people see social media as an entertainment factor, and this easily captures their attention.",
    gradable: true,
    raw: "Many people see social media as an entertainment factor. This easily captures their attention."
  },
  {
    id: "devjourn-64",
    module: "Lesson 3",
    number: 64,
    topic: "ICT4D",
    question: "64. The Arab Spring example in the ICT4D section began with Mohamed Bouzazi doing what?",
    choices: ["setting himself on fire as protest after being harassed by public officials", "starting a radio station for celebrity news", "creating a government monopoly", "writing an ACL"],
    answers: ["setting himself on fire as protest after being harassed by public officials"],
    matching: null,
    images: [],
    explanation: "The reviewer says Mohamed Bouzazi set himself on fire as protest after being harassed by public officials.",
    gradable: true,
    raw: "Dec 17, 2010 named Mohamed Bouzazi set himself on fire as protest as being harassed by public officials."
  },
  {
    id: "devjourn-65",
    module: "Lesson 3",
    number: 65,
    topic: "ICT4D",
    question: "65. Which type of digital divide is described by men having more mobile phone access than women in low income countries?",
    choices: ["Gender Divide", "Universal Access Divide", "Social Divide", "Communication Planning"],
    answers: ["Gender Divide"],
    matching: null,
    images: [],
    explanation: "The reviewer gives this example under Gender Divide.",
    gradable: true,
    raw: "Gender Divide: men in low income countries are more likely to own a mobile phone than women."
  },
  {
    id: "devjourn-66",
    module: "Lesson 3",
    number: 66,
    topic: "Communication Planning",
    question: "66. Communication Problem identification refers to gaps in what focused-audience areas? (Choose four.)",
    choices: ["knowledge", "attitude", "skill", "practice/behavior", "celebrity visibility", "router access"],
    answers: ["knowledge", "attitude", "skill", "practice/behavior"],
    matching: null,
    images: [],
    explanation: "The reviewer says communication problem identification refers to gaps in knowledge, attitude, skill, and/or practice/behavior of the focused audience.",
    gradable: true,
    raw: "Communication Problem - Issues Identification refers to the gaps in the knowledge, attitude, skill, and or practice/behavior of the focused audience."
  },
  {
    id: "devjourn-67",
    module: "Lesson 3",
    number: 67,
    topic: "Communication Planning",
    question: "67. Monitoring and evaluation scheme measures what?",
    choices: ["the progress achieved in planning and managing a program or project", "celebrity influence only", "the number of router ports", "only government propaganda"],
    answers: ["the progress achieved in planning and managing a program or project"],
    matching: null,
    images: [],
    explanation: "The reviewer says monitoring and evaluation measures progress achieved in planning and managing a program or project.",
    gradable: true,
    raw: "Monitoring and evaluation scheme measures the progress achieved in planning and managing a program or project."
  },
  {
    id: "devjourn-68",
    module: "Lesson 4",
    number: 68,
    topic: "NGOs",
    question: "68. According to the notes, what did the World Bank realize about NGOs in the 1980s?",
    choices: ["NGOs are less corrupt and more effective than the government", "NGOs should never work with communities", "NGOs only started in 2001", "NGOs are the same as celebrity media"],
    answers: ["NGOs are less corrupt and more effective than the government"],
    matching: null,
    images: [],
    explanation: "The reviewer says that in the 1980s the World Bank realized NGOs are less corrupt and more effective than the government.",
    gradable: true,
    raw: "1980s the World Bank realized NGO is less corrupt and most effective than the government."
  },
  {
    id: "devjourn-69",
    module: "Lesson 4",
    number: 69,
    topic: "Community Broadcasting",
    question: "69. In community broadcasting, why is language important?",
    choices: ["language spoken and understood is the key consideration", "language should hide community needs", "language is only for advertising", "language replaces public interest"],
    answers: ["language spoken and understood is the key consideration"],
    matching: null,
    images: [],
    explanation: "The reviewer says language which is spoken and understood is the key consideration.",
    gradable: true,
    raw: "Language which is spoken and understood is the key consideration."
  },
  {
    id: "devjourn-70",
    module: "Lesson 4",
    number: 70,
    topic: "Celebrity Media",
    question: "70. What is one problem involving celebrity media according to the reviewer?",
    choices: ["the audience may focus on the celebrity and drown away the purpose of the event", "the audience always ignores celebrities", "celebrity media started in 1839", "celebrities remove all need for action"],
    answers: ["the audience may focus on the celebrity and drown away the purpose of the event"],
    matching: null,
    images: [],
    explanation: "The reviewer warns that the audience can focus on the celebrity and drown away the purpose of the event.",
    gradable: true,
    raw: "Problem involving celeb: Audience will focus at the celeb and they will drown away by the purpose of the event."
  }
];
